In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,classification_report,f1_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
x,y=make_regression(n_samples=1000,n_features=3,random_state=42)
print(x)
print(y)

[[-0.5391227  -0.60787526 -0.83726243]
 [-1.4066611  -0.6115178  -0.75538293]
 [ 0.68189149  1.04416088 -0.48943944]
 ...
 [ 0.6404798  -0.46649538  0.99657051]
 [-1.13883312  0.62220714  0.30047436]
 [-0.95643638 -1.29327296  0.71975794]]
[-1.42338105e+02 -1.58520012e+02  8.03345971e+01 -1.68176389e+02
  1.81493775e+02  1.04678329e+02  2.02397931e+02 -1.18139772e+02
 -9.77690126e+01  2.89617852e+01 -3.73589172e+01  1.20328037e+02
  3.60634016e+01 -1.38066226e+02  2.01625663e+02  1.77481385e+02
  1.78713265e+02  1.33321395e+02  2.77336225e+01 -2.84102770e+01
  4.13132572e+01  2.28608309e+02 -3.14158826e+01 -1.33728801e+01
 -9.93324279e+01 -4.97151414e+01 -1.08320706e+02 -8.85686626e+01
  1.96209329e+02  3.21662512e+01  6.22223526e+00 -9.89209172e+01
 -1.22413703e+02 -1.82923988e+02 -1.20697452e+02  9.07472329e+01
 -1.27414226e+02  1.19537688e+02 -3.93122933e+01 -1.31413437e+02
 -7.57339501e+01 -1.17324025e+02  1.22753511e+02 -6.08892589e+01
 -1.14728623e+02  2.48701884e+02  7.90059046e

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
c1=KNeighborsRegressor(n_neighbors=5,algorithm='auto')
c1.fit(x_train,y_train)

KNeighborsRegressor()

In [18]:
y_pred=c1.predict(x_test)

In [20]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
rmse=np.sqrt(mse)
print("Mean Squared Error:",mse)
print("Root Mean Squared Error:",rmse)
print("Mean Absolute Error:",mae)
print("R2-Score:",r2)

Mean Squared Error: 428.9789329594436
Root Mean Squared Error: 20.711806607812935
Mean Absolute Error: 12.998096712498993
R2-Score: 0.975382121239828
